spring.application.name=api-gateway

gateway.product-service.uri=http://product-service:8080
gateway.order-service.uri=http://order-service:8083
gateway.inventory-service.uri=http://inventory-service:8082

server.port=9000
logging.level.root=DEBUG
