# ====================================
#    APPLICATION CONFIG
# ====================================
spring.application.name=api-gateway

gateway.product-service.uri=http://product-service:8080
gateway.order-service.uri=http://order-service:8083
gateway.inventory-service.uri=http://inventory-service:8082

server.forward-headers-strategy=framework

server.port=9000

# ====================================
#    LOGGING CONFIGURATION
# ====================================
ogging.level.root=DEBUG
logging.level.com.akul.microservices=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.web.client=DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.oauth2=DEBUG
#logging.pattern.console={"time":"%d{yyyy-MM-dd HH:mm:ss}", "level":"%level",  "thread":"%thread", "logger":"%logger", "service":"${spring.application.name}", "message":"%msg"}%n

# ====================================
#    ACTUATOR / PROMETHEUS / TRACING
# ====================================
management.endpoints.web.exposure.include=health,info,metrics,prometheus
management.metrics.distribution.percentiles-histogram.http.server.requests=true
management.observations.key-values.application=${spring.application.name}
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://tempo:9411/api/v2/spans
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true

# ====================================
#    SECURITY (Keycloak)
# ====================================
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://host.docker.internal:8181/realms/MicroServicesGrid-realm
spring.security.oauth2.resourceserver.jwt.authorities-claim-name=realm_access.roles
spring.security.oauth2.resourceserver.jwt.authorities-prefix=ROLE_
# CORS
cors.allowed-origins=http://localhost:4200
cors.allowed-methods=*
cors.allowed-headers=*
cors.allow-credentials=true
# ====================================
#    ACTUATOR + HEALTH
# ====================================
management.endpoints.web.exposure.include=*
management.endpoint.health.show-details=always
management.health.circuitbreakers.enabled=true

# ====================================
#    GATEWAY ROUTES + CIRCUIT BREAKERS
# ====================================

# ---------- ORDER SERVICE ----------
spring.cloud.gateway.routes[0].id=order-service
spring.cloud.gateway.routes[0].uri=lb://ORDER-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/orders/**
spring.cloud.gateway.routes[0].filters[0].name=CircuitBreaker
spring.cloud.gateway.routes[0].filters[0].args.name=orderServiceCB
spring.cloud.gateway.routes[0].filters[0].args.fallbackUri=forward:/fallback/orders
spring.cloud.gateway.routes[0].filters[1].name=RequestRateLimiter
spring.cloud.gateway.routes[0].filters[1].args.redis-rate-limiter.replenishRate=5
spring.cloud.gateway.routes[0].filters[1].args.redis-rate-limiter.burstCapacity=10

# ---------- PRODUCT SERVICE ----------
spring.cloud.gateway.routes[1].id=product-service
spring.cloud.gateway.routes[1].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/v1/products/**
# ---------- INVENTORY SERVICE ----------
spring.cloud.gateway.routes[2].id=inventory-service
spring.cloud.gateway.routes[2].uri=lb://INVENTORY-SERVICE
spring.cloud.gateway.routes[2].predicates[0]=Path=/api/inventory/**
spring.cloud.gateway.routes[2].filters[0].name=CircuitBreaker
spring.cloud.gateway.routes[2].filters[0].args.name=inventoryServiceCB
spring.cloud.gateway.routes[2].filters[0].args.fallbackUri=forward:/fallback/inventory
spring.cloud.gateway.routes[2].filters[1].name=RequestRateLimiter
spring.cloud.gateway.routes[2].filters[1].args.redis-rate-limiter.replenishRate=5
spring.cloud.gateway.routes[2].filters[1].args.redis-rate-limiter.burstCapacity=10

# ---------- PRODUCT ADMIN SERVICE ----------
spring.cloud.gateway.routes[3].id=product-admin-service
spring.cloud.gateway.routes[3].uri=lb://PRODUCT-SERVICE
spring.cloud.gateway.routes[3].predicates[0]=Path=/api/v1/admin/products/**

# ====================================
#   RESILIENCE4J CONFIGURATION
# ====================================

# ----- Base Defaults -----
resilience4j.circuitbreaker.configs.default.registerHealthIndicator=true
resilience4j.circuitbreaker.configs.default.slidingWindowType=COUNT_BASED
resilience4j.circuitbreaker.configs.default.slidingWindowSize=10
resilience4j.circuitbreaker.configs.default.failureRateThreshold=50
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=5s
resilience4j.circuitbreaker.configs.default.permittedNumberOfCallsInHalfOpenState=3
resilience4j.circuitbreaker.configs.default.automaticTransitionFromOpenToHalfOpenEnabled=true
resilience4j.circuitbreaker.configs.default.minimumNumberOfCalls=5

# ----- Timeout -----
resilience4j.timelimiter.configs.default.timeout-duration=3s

# ----- Retry -----
resilience4j.retry.configs.default.max-attempts=3
resilience4j.retry.configs.default.wait-duration=2s

# ----- Instances -----
resilience4j.circuitbreaker.instances.orderServiceCB.baseConfig=default
resilience4j.circuitbreaker.instances.productServiceCB.baseConfig=default
resilience4j.circuitbreaker.instances.inventoryServiceCB.baseConfig=default

resilience4j.retry.instances.orderServiceCB.baseConfig=default
resilience4j.retry.instances.productServiceCB.baseConfig=default
resilience4j.retry.instances.inventoryServiceCB.baseConfig=default

resilience4j.timelimiter.instances.orderServiceCB.baseConfig=default
resilience4j.timelimiter.instances.productServiceCB.baseConfig=default
resilience4j.timelimiter.instances.inventoryServiceCB.baseConfig=default

# ====================================
#   REDIS (Rate Limiter)
# ====================================
spring.data.redis.host=redis
spring.data.redis.port=6379

# ====================================
#   DISCOVERY
# ====================================
spring.cloud.gateway.discovery.locator.enabled=true
spring.cloud.gateway.discovery.locator.lower-case-service-id=true

eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/



